### PR TITLE
Made changes to deployment in style.css

### PR DESCRIPTION
**Pull request by evansnyamekye**
Made changes to deployment in style.css

### CODE REVIEW

**Comment by koachcode** [comment]
@evansnyamekye I can not seem to locate your Deployed link for accessing the portfolio website, I check the readme for the new-deployment branch as well as the Main Branch. Please do well to add the Live deployed linked to your README.md  or in your PR.

The image below is what you have in your readme for both the new-deployment and the main branch 

image

**Review by koachcode — COMMENTED** [review]
Hi @evansnyamekye, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
you-are-near

## Highlights


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- No deployment link of Live Portfolio

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by evansnyamekye** [comment]
@Ginohmk this actually escaped me. I have made the necessary corrections. 😀

**Comment by didierganthier** [comment]
@evansnyamekye where is the deployment link?

**Comment by evansnyamekye** [comment]
@didierganthier https://evansnyamekye.github.io/Portfolio-CompleteWebsite/

**Comment by didierganthier** [comment]
Good but also make sure that the README is updated to include a link to the online version. Remember the `Live Demo` section? You can add it again. @evansnyamekye

**Comment by evansnyamekye** [comment]
@didierganthier I have already done that. I realized my submission is saying review pending. do I have to submit it again??

**Review by didierganthier — COMMENTED** [review]
Hi @evansnyamekye ,

Congratulations! 🎉 Your project is complete and ready! 🚀



## Highlights
- Deployed successfully ✔️ 
- Used GitHub Pages ✔️ 
- Included Link in README ✔️ 

## Optional Suggestions 💡
- [ ] Well done on the deployment 🚀 but consider using the same section you had in the README previously to put back in this README and consider updating the Table of Contents as well. 💯 

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

**Pull request merged**
